name: motor_secure
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  connectivity_plus: ^5.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0
  font_awesome_icon_class: ^0.0.6
  gap: ^3.0.1
  geolocator: ^11.1.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.12.1
  http: ^1.3.0
  intl: ^0.20.2
  mailer: ^6.1.0
  permission_handler: ^12.0.0+1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.5.3
  string_validator: ^1.1.0
  stylish_bottom_bar: ^1.1.1
  url_launcher: ^6.2.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/sounds/

